// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/medicines": {
    params: {};
  };
  "/medicines/catalog": {
    params: {};
  };
  "/medicines/categories": {
    params: {};
  };
  "/medicines/manufacturers": {
    params: {};
  };
  "/medicines/:medicineId": {
    params: {
      "medicineId": string;
    };
  };
  "/batches": {
    params: {};
  };
  "/batches/:batchId": {
    params: {
      "batchId": string;
    };
  };
  "/sales": {
    params: {};
  };
  "/sales/:saleId": {
    params: {
      "saleId": string;
    };
  };
  "/purchases": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/expiry": {
    params: {};
  };
  "/audit": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/ai": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/forgot-password" | "/dashboard" | "/medicines" | "/medicines/catalog" | "/medicines/categories" | "/medicines/manufacturers" | "/medicines/:medicineId" | "/batches" | "/batches/:batchId" | "/sales" | "/sales/:saleId" | "/purchases" | "/inventory" | "/expiry" | "/audit" | "/reports" | "/users" | "/ai" | "/notifications" | "/admin";
  };
  "pages/LandingPage.jsx": {
    id: "pages/LandingPage";
    page: "/";
  };
  "pages/LoginPage.jsx": {
    id: "pages/LoginPage";
    page: "/login";
  };
  "pages/SignupPage.jsx": {
    id: "pages/SignupPage";
    page: "/signup";
  };
  "pages/ForgotPasswordPage.jsx": {
    id: "pages/ForgotPasswordPage";
    page: "/forgot-password";
  };
  "layouts/AppLayout.jsx": {
    id: "layouts/AppLayout";
    page: "/dashboard" | "/medicines" | "/medicines/catalog" | "/medicines/categories" | "/medicines/manufacturers" | "/medicines/:medicineId" | "/batches" | "/batches/:batchId" | "/sales" | "/sales/:saleId" | "/purchases" | "/inventory" | "/expiry" | "/audit" | "/reports" | "/users" | "/ai" | "/notifications" | "/admin";
  };
  "pages/dashboard/DashboardHomePage.jsx": {
    id: "pages/dashboard/DashboardHomePage";
    page: "/dashboard";
  };
  "pages/medicines/MedicinesStorePage.jsx": {
    id: "pages/medicines/MedicinesStorePage";
    page: "/medicines";
  };
  "pages/medicines/MedicinesCatalogPage.jsx": {
    id: "pages/medicines/MedicinesCatalogPage";
    page: "/medicines/catalog";
  };
  "pages/medicines/CategoriesPage.jsx": {
    id: "pages/medicines/CategoriesPage";
    page: "/medicines/categories";
  };
  "pages/medicines/ManufacturersPage.jsx": {
    id: "pages/medicines/ManufacturersPage";
    page: "/medicines/manufacturers";
  };
  "pages/medicines/MedicineDetailPage.jsx": {
    id: "pages/medicines/MedicineDetailPage";
    page: "/medicines/:medicineId";
  };
  "pages/batches/BatchesPage.jsx": {
    id: "pages/batches/BatchesPage";
    page: "/batches";
  };
  "pages/batches/BatchDetailPage.jsx": {
    id: "pages/batches/BatchDetailPage";
    page: "/batches/:batchId";
  };
  "pages/sales/SalesPage.jsx": {
    id: "pages/sales/SalesPage";
    page: "/sales";
  };
  "pages/sales/SaleDetailPage.jsx": {
    id: "pages/sales/SaleDetailPage";
    page: "/sales/:saleId";
  };
  "pages/purchases/PurchasesPage.jsx": {
    id: "pages/purchases/PurchasesPage";
    page: "/purchases";
  };
  "pages/inventory/InventoryPage.jsx": {
    id: "pages/inventory/InventoryPage";
    page: "/inventory";
  };
  "pages/expiry/ExpiryPage.jsx": {
    id: "pages/expiry/ExpiryPage";
    page: "/expiry";
  };
  "pages/audit/AuditPage.jsx": {
    id: "pages/audit/AuditPage";
    page: "/audit";
  };
  "pages/reports/ReportsPage.jsx": {
    id: "pages/reports/ReportsPage";
    page: "/reports";
  };
  "pages/users/UsersPage.jsx": {
    id: "pages/users/UsersPage";
    page: "/users";
  };
  "pages/ai/AiAssistantPage.jsx": {
    id: "pages/ai/AiAssistantPage";
    page: "/ai";
  };
  "pages/notifications/NotificationsPage.jsx": {
    id: "pages/notifications/NotificationsPage";
    page: "/notifications";
  };
  "pages/admin/AdminPage.jsx": {
    id: "pages/admin/AdminPage";
    page: "/admin";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/LandingPage": typeof import("./src/pages/LandingPage.jsx");
  "pages/LoginPage": typeof import("./src/pages/LoginPage.jsx");
  "pages/SignupPage": typeof import("./src/pages/SignupPage.jsx");
  "pages/ForgotPasswordPage": typeof import("./src/pages/ForgotPasswordPage.jsx");
  "layouts/AppLayout": typeof import("./src/layouts/AppLayout.jsx");
  "pages/dashboard/DashboardHomePage": typeof import("./src/pages/dashboard/DashboardHomePage.jsx");
  "pages/medicines/MedicinesStorePage": typeof import("./src/pages/medicines/MedicinesStorePage.jsx");
  "pages/medicines/MedicinesCatalogPage": typeof import("./src/pages/medicines/MedicinesCatalogPage.jsx");
  "pages/medicines/CategoriesPage": typeof import("./src/pages/medicines/CategoriesPage.jsx");
  "pages/medicines/ManufacturersPage": typeof import("./src/pages/medicines/ManufacturersPage.jsx");
  "pages/medicines/MedicineDetailPage": typeof import("./src/pages/medicines/MedicineDetailPage.jsx");
  "pages/batches/BatchesPage": typeof import("./src/pages/batches/BatchesPage.jsx");
  "pages/batches/BatchDetailPage": typeof import("./src/pages/batches/BatchDetailPage.jsx");
  "pages/sales/SalesPage": typeof import("./src/pages/sales/SalesPage.jsx");
  "pages/sales/SaleDetailPage": typeof import("./src/pages/sales/SaleDetailPage.jsx");
  "pages/purchases/PurchasesPage": typeof import("./src/pages/purchases/PurchasesPage.jsx");
  "pages/inventory/InventoryPage": typeof import("./src/pages/inventory/InventoryPage.jsx");
  "pages/expiry/ExpiryPage": typeof import("./src/pages/expiry/ExpiryPage.jsx");
  "pages/audit/AuditPage": typeof import("./src/pages/audit/AuditPage.jsx");
  "pages/reports/ReportsPage": typeof import("./src/pages/reports/ReportsPage.jsx");
  "pages/users/UsersPage": typeof import("./src/pages/users/UsersPage.jsx");
  "pages/ai/AiAssistantPage": typeof import("./src/pages/ai/AiAssistantPage.jsx");
  "pages/notifications/NotificationsPage": typeof import("./src/pages/notifications/NotificationsPage.jsx");
  "pages/admin/AdminPage": typeof import("./src/pages/admin/AdminPage.jsx");
};