import { SiGmail, SiQuickbooks, SiRazorpay, SiStripe, SiWhatsapp, SiZoho } from "react-icons/si";
import {
  Bike,
  Cloud,
  ExternalLink,
  FileSignature,
  HeartPulse,
  Landmark,
  LayoutDashboard,
  Send,
  UserPlus,
} from "lucide-react";

export const INTEGRATION_CATEGORIES = [
  { key: "communication", label: "Communication" },
  { key: "healthcare", label: "Healthcare & Medical" },
  { key: "accounting", label: "Accounting & Tax" },
  { key: "payments", label: "Payments" },
  { key: "cloud", label: "Cloud & Storage" },
  { key: "delivery", label: "Delivery & Logistics" },
];

export const INTEGRATIONS = [
  {
    key: "whatsapp",
    name: "WhatsApp Business",
    category: "communication",
    description: "Customer communication and pharmacy notifications via WhatsApp Business.",
    capabilities: ["Order Updates", "Invoice Messages", "Delivery Notifications", "Expiry Alerts"],
    icon: SiWhatsapp,
    primaryAction: { label: "Open WhatsApp", icon: ExternalLink },
  },
  {
    key: "gmail",
    name: "Gmail",
    category: "communication",
    description: "Send invoices, reports, and notifications from your pharmacy email.",
    capabilities: ["Send Invoices", "Send Reports", "Email Notifications"],
    icon: SiGmail,
    primaryAction: { label: "Send Email", icon: Send },
  },
  {
    key: "abdmHealthId",
    name: "ABDM Health ID",
    category: "healthcare",
    description: "Connect with the healthcare ecosystem to manage patient Health IDs.",
    capabilities: ["Create Health ID", "Link Patient Records", "Share Health Data"],
    icon: HeartPulse,
    primaryAction: { label: "Create Health ID", icon: UserPlus },
  },
  {
    key: "ePrescription",
    name: "E-Prescription Service",
    category: "healthcare",
    description: "Issue and manage digital prescriptions for pharmacy patients.",
    capabilities: ["Send Prescriptions", "Electronic Signing", "Prescription Records"],
    icon: FileSignature,
    primaryAction: { label: "Send Prescription", icon: FileSignature },
  },
  {
    key: "quickbooks",
    name: "QuickBooks",
    category: "accounting",
    description: "Accounting and invoicing for pharmacy bookkeeping.",
    capabilities: ["Invoice Sync", "Expense Tracking", "Tax Reports"],
    icon: SiQuickbooks,
    primaryAction: { label: "Open Dashboard", icon: LayoutDashboard },
  },
  {
    key: "zohoBooks",
    name: "Zoho Books",
    category: "accounting",
    description: "Online accounting for pharmacy financial records.",
    capabilities: ["Invoice Sync", "Expense Tracking", "Financial Reports"],
    icon: SiZoho,
    primaryAction: { label: "Open Dashboard", icon: LayoutDashboard },
  },
  {
    key: "gstFiling",
    name: "GST Filing",
    category: "accounting",
    description: "Prepare and file pharmacy GST returns from your sales and purchase data.",
    capabilities: ["GSTR-1", "GSTR-3B", "Tax Reports"],
    icon: Landmark,
    primaryAction: { label: "Open Portal", icon: LayoutDashboard },
  },
  {
    key: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Accept card payments for pharmacy transactions.",
    capabilities: ["Card Payments", "Payment Links", "Refund Processing"],
    icon: SiStripe,
    primaryAction: { label: "Open Dashboard", icon: LayoutDashboard },
  },
  {
    key: "razorpay",
    name: "Razorpay",
    category: "payments",
    description: "UPI and online payments for Indian pharmacy sales.",
    capabilities: ["UPI Payments", "Payment Links", "Settlement Reports"],
    icon: SiRazorpay,
    primaryAction: { label: "Open Dashboard", icon: LayoutDashboard },
  },
  {
    key: "googleDrive",
    name: "Google Drive",
    category: "cloud",
    description: "Back up invoices, reports, and pharmacy documents to cloud storage.",
    capabilities: ["Backup Documents", "Share Reports", "Store Invoices"],
    icon: Cloud,
    primaryAction: { label: "Open Drive", icon: ExternalLink },
  },
  {
    key: "medicineDelivery",
    name: "Medicine Delivery",
    category: "delivery",
    description: "Local delivery partners for doorstep medicine orders.",
    capabilities: ["Schedule Pickups", "Track Deliveries", "Delivery Updates"],
    icon: Bike,
    primaryAction: { label: "Book Delivery", icon: Bike },
  },
];
