/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated.dashboard.admin'
import { Route as AuthenticatedDashboardAiRouteImport } from './routes/_authenticated.dashboard.ai'
import { Route as AuthenticatedDashboardAuditRouteImport } from './routes/_authenticated.dashboard.audit'
import { Route as AuthenticatedDashboardBatchesRouteImport } from './routes/_authenticated.dashboard.batches'
import { Route as AuthenticatedDashboardExpiryRouteImport } from './routes/_authenticated.dashboard.expiry'
import { Route as AuthenticatedDashboardInventoryRouteImport } from './routes/_authenticated.dashboard.inventory'
import { Route as AuthenticatedDashboardMedicinesRouteImport } from './routes/_authenticated.dashboard.medicines'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated.dashboard.notifications'
import { Route as AuthenticatedDashboardPurchasesRouteImport } from './routes/_authenticated.dashboard.purchases'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated.dashboard.reports'
import { Route as AuthenticatedDashboardSalesRouteImport } from './routes/_authenticated.dashboard.sales'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated.dashboard.users'
import { Route as AuthenticatedDashboardBatchesBatchIdRouteImport } from './routes/_authenticated.dashboard.batches.$batchId'
import { Route as AuthenticatedDashboardMedicinesIndexRouteImport } from './routes/_authenticated.dashboard.medicines.index'
import { Route as AuthenticatedDashboardMedicinesMedicineIdRouteImport } from './routes/_authenticated.dashboard.medicines.$medicineId'
import { Route as AuthenticatedDashboardMedicinesCategoriesRouteImport } from './routes/_authenticated.dashboard.medicines.categories'
import { Route as AuthenticatedDashboardMedicinesManufacturersRouteImport } from './routes/_authenticated.dashboard.medicines.manufacturers'
import { Route as AuthenticatedDashboardSalesSaleIdRouteImport } from './routes/_authenticated.dashboard.sales.$saleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiRoute =
  AuthenticatedDashboardAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAuditRoute =
  AuthenticatedDashboardAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBatchesRoute =
  AuthenticatedDashboardBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardExpiryRoute =
  AuthenticatedDashboardExpiryRouteImport.update({
    id: '/expiry',
    path: '/expiry',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInventoryRoute =
  AuthenticatedDashboardInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMedicinesRoute =
  AuthenticatedDashboardMedicinesRouteImport.update({
    id: '/medicines',
    path: '/medicines',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPurchasesRoute =
  AuthenticatedDashboardPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSalesRoute =
  AuthenticatedDashboardSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBatchesBatchIdRoute =
  AuthenticatedDashboardBatchesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedDashboardBatchesRoute,
  } as any)
const AuthenticatedDashboardMedicinesIndexRoute =
  AuthenticatedDashboardMedicinesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardMedicinesRoute,
  } as any)
const AuthenticatedDashboardMedicinesMedicineIdRoute =
  AuthenticatedDashboardMedicinesMedicineIdRouteImport.update({
    id: '/$medicineId',
    path: '/$medicineId',
    getParentRoute: () => AuthenticatedDashboardMedicinesRoute,
  } as any)
const AuthenticatedDashboardMedicinesCategoriesRoute =
  AuthenticatedDashboardMedicinesCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardMedicinesRoute,
  } as any)
const AuthenticatedDashboardMedicinesManufacturersRoute =
  AuthenticatedDashboardMedicinesManufacturersRouteImport.update({
    id: '/manufacturers',
    path: '/manufacturers',
    getParentRoute: () => AuthenticatedDashboardMedicinesRoute,
  } as any)
const AuthenticatedDashboardSalesSaleIdRoute =
  AuthenticatedDashboardSalesSaleIdRouteImport.update({
    id: '/$saleId',
    path: '/$saleId',
    getParentRoute: () => AuthenticatedDashboardSalesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/ai': typeof AuthenticatedDashboardAiRoute
  '/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/dashboard/batches': typeof AuthenticatedDashboardBatchesRouteWithChildren
  '/dashboard/expiry': typeof AuthenticatedDashboardExpiryRoute
  '/dashboard/inventory': typeof AuthenticatedDashboardInventoryRoute
  '/dashboard/medicines': typeof AuthenticatedDashboardMedicinesRouteWithChildren
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/sales': typeof AuthenticatedDashboardSalesRouteWithChildren
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/batches/$batchId': typeof AuthenticatedDashboardBatchesBatchIdRoute
  '/dashboard/medicines/$medicineId': typeof AuthenticatedDashboardMedicinesMedicineIdRoute
  '/dashboard/medicines/categories': typeof AuthenticatedDashboardMedicinesCategoriesRoute
  '/dashboard/medicines/manufacturers': typeof AuthenticatedDashboardMedicinesManufacturersRoute
  '/dashboard/sales/$saleId': typeof AuthenticatedDashboardSalesSaleIdRoute
  '/dashboard/medicines/': typeof AuthenticatedDashboardMedicinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/ai': typeof AuthenticatedDashboardAiRoute
  '/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/dashboard/batches': typeof AuthenticatedDashboardBatchesRouteWithChildren
  '/dashboard/expiry': typeof AuthenticatedDashboardExpiryRoute
  '/dashboard/inventory': typeof AuthenticatedDashboardInventoryRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/sales': typeof AuthenticatedDashboardSalesRouteWithChildren
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/batches/$batchId': typeof AuthenticatedDashboardBatchesBatchIdRoute
  '/dashboard/medicines/$medicineId': typeof AuthenticatedDashboardMedicinesMedicineIdRoute
  '/dashboard/medicines/categories': typeof AuthenticatedDashboardMedicinesCategoriesRoute
  '/dashboard/medicines/manufacturers': typeof AuthenticatedDashboardMedicinesManufacturersRoute
  '/dashboard/sales/$saleId': typeof AuthenticatedDashboardSalesSaleIdRoute
  '/dashboard/medicines': typeof AuthenticatedDashboardMedicinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/ai': typeof AuthenticatedDashboardAiRoute
  '/_authenticated/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/_authenticated/dashboard/batches': typeof AuthenticatedDashboardBatchesRouteWithChildren
  '/_authenticated/dashboard/expiry': typeof AuthenticatedDashboardExpiryRoute
  '/_authenticated/dashboard/inventory': typeof AuthenticatedDashboardInventoryRoute
  '/_authenticated/dashboard/medicines': typeof AuthenticatedDashboardMedicinesRouteWithChildren
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/sales': typeof AuthenticatedDashboardSalesRouteWithChildren
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/batches/$batchId': typeof AuthenticatedDashboardBatchesBatchIdRoute
  '/_authenticated/dashboard/medicines/$medicineId': typeof AuthenticatedDashboardMedicinesMedicineIdRoute
  '/_authenticated/dashboard/medicines/categories': typeof AuthenticatedDashboardMedicinesCategoriesRoute
  '/_authenticated/dashboard/medicines/manufacturers': typeof AuthenticatedDashboardMedicinesManufacturersRoute
  '/_authenticated/dashboard/sales/$saleId': typeof AuthenticatedDashboardSalesSaleIdRoute
  '/_authenticated/dashboard/medicines/': typeof AuthenticatedDashboardMedicinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/ai'
    | '/dashboard/audit'
    | '/dashboard/batches'
    | '/dashboard/expiry'
    | '/dashboard/inventory'
    | '/dashboard/medicines'
    | '/dashboard/notifications'
    | '/dashboard/purchases'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/batches/$batchId'
    | '/dashboard/medicines/$medicineId'
    | '/dashboard/medicines/categories'
    | '/dashboard/medicines/manufacturers'
    | '/dashboard/sales/$saleId'
    | '/dashboard/medicines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/ai'
    | '/dashboard/audit'
    | '/dashboard/batches'
    | '/dashboard/expiry'
    | '/dashboard/inventory'
    | '/dashboard/notifications'
    | '/dashboard/purchases'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/batches/$batchId'
    | '/dashboard/medicines/$medicineId'
    | '/dashboard/medicines/categories'
    | '/dashboard/medicines/manufacturers'
    | '/dashboard/sales/$saleId'
    | '/dashboard/medicines'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/ai'
    | '/_authenticated/dashboard/audit'
    | '/_authenticated/dashboard/batches'
    | '/_authenticated/dashboard/expiry'
    | '/_authenticated/dashboard/inventory'
    | '/_authenticated/dashboard/medicines'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/purchases'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/sales'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/batches/$batchId'
    | '/_authenticated/dashboard/medicines/$medicineId'
    | '/_authenticated/dashboard/medicines/categories'
    | '/_authenticated/dashboard/medicines/manufacturers'
    | '/_authenticated/dashboard/sales/$saleId'
    | '/_authenticated/dashboard/medicines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai': {
      id: '/_authenticated/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof AuthenticatedDashboardAiRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/audit': {
      id: '/_authenticated/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof AuthenticatedDashboardAuditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/batches': {
      id: '/_authenticated/dashboard/batches'
      path: '/batches'
      fullPath: '/dashboard/batches'
      preLoaderRoute: typeof AuthenticatedDashboardBatchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/expiry': {
      id: '/_authenticated/dashboard/expiry'
      path: '/expiry'
      fullPath: '/dashboard/expiry'
      preLoaderRoute: typeof AuthenticatedDashboardExpiryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inventory': {
      id: '/_authenticated/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof AuthenticatedDashboardInventoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/medicines': {
      id: '/_authenticated/dashboard/medicines'
      path: '/medicines'
      fullPath: '/dashboard/medicines'
      preLoaderRoute: typeof AuthenticatedDashboardMedicinesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/purchases': {
      id: '/_authenticated/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof AuthenticatedDashboardPurchasesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sales': {
      id: '/_authenticated/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof AuthenticatedDashboardSalesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/batches/$batchId': {
      id: '/_authenticated/dashboard/batches/$batchId'
      path: '/$batchId'
      fullPath: '/dashboard/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedDashboardBatchesBatchIdRouteImport
      parentRoute: typeof AuthenticatedDashboardBatchesRoute
    }
    '/_authenticated/dashboard/medicines/': {
      id: '/_authenticated/dashboard/medicines/'
      path: '/'
      fullPath: '/dashboard/medicines/'
      preLoaderRoute: typeof AuthenticatedDashboardMedicinesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardMedicinesRoute
    }
    '/_authenticated/dashboard/medicines/$medicineId': {
      id: '/_authenticated/dashboard/medicines/$medicineId'
      path: '/$medicineId'
      fullPath: '/dashboard/medicines/$medicineId'
      preLoaderRoute: typeof AuthenticatedDashboardMedicinesMedicineIdRouteImport
      parentRoute: typeof AuthenticatedDashboardMedicinesRoute
    }
    '/_authenticated/dashboard/medicines/categories': {
      id: '/_authenticated/dashboard/medicines/categories'
      path: '/categories'
      fullPath: '/dashboard/medicines/categories'
      preLoaderRoute: typeof AuthenticatedDashboardMedicinesCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardMedicinesRoute
    }
    '/_authenticated/dashboard/medicines/manufacturers': {
      id: '/_authenticated/dashboard/medicines/manufacturers'
      path: '/manufacturers'
      fullPath: '/dashboard/medicines/manufacturers'
      preLoaderRoute: typeof AuthenticatedDashboardMedicinesManufacturersRouteImport
      parentRoute: typeof AuthenticatedDashboardMedicinesRoute
    }
    '/_authenticated/dashboard/sales/$saleId': {
      id: '/_authenticated/dashboard/sales/$saleId'
      path: '/$saleId'
      fullPath: '/dashboard/sales/$saleId'
      preLoaderRoute: typeof AuthenticatedDashboardSalesSaleIdRouteImport
      parentRoute: typeof AuthenticatedDashboardSalesRoute
    }
  }
}

interface AuthenticatedDashboardBatchesRouteChildren {
  AuthenticatedDashboardBatchesBatchIdRoute: typeof AuthenticatedDashboardBatchesBatchIdRoute
}

const AuthenticatedDashboardBatchesRouteChildren: AuthenticatedDashboardBatchesRouteChildren =
  {
    AuthenticatedDashboardBatchesBatchIdRoute:
      AuthenticatedDashboardBatchesBatchIdRoute,
  }

const AuthenticatedDashboardBatchesRouteWithChildren =
  AuthenticatedDashboardBatchesRoute._addFileChildren(
    AuthenticatedDashboardBatchesRouteChildren,
  )

interface AuthenticatedDashboardMedicinesRouteChildren {
  AuthenticatedDashboardMedicinesMedicineIdRoute: typeof AuthenticatedDashboardMedicinesMedicineIdRoute
  AuthenticatedDashboardMedicinesCategoriesRoute: typeof AuthenticatedDashboardMedicinesCategoriesRoute
  AuthenticatedDashboardMedicinesManufacturersRoute: typeof AuthenticatedDashboardMedicinesManufacturersRoute
  AuthenticatedDashboardMedicinesIndexRoute: typeof AuthenticatedDashboardMedicinesIndexRoute
}

const AuthenticatedDashboardMedicinesRouteChildren: AuthenticatedDashboardMedicinesRouteChildren =
  {
    AuthenticatedDashboardMedicinesMedicineIdRoute:
      AuthenticatedDashboardMedicinesMedicineIdRoute,
    AuthenticatedDashboardMedicinesCategoriesRoute:
      AuthenticatedDashboardMedicinesCategoriesRoute,
    AuthenticatedDashboardMedicinesManufacturersRoute:
      AuthenticatedDashboardMedicinesManufacturersRoute,
    AuthenticatedDashboardMedicinesIndexRoute:
      AuthenticatedDashboardMedicinesIndexRoute,
  }

const AuthenticatedDashboardMedicinesRouteWithChildren =
  AuthenticatedDashboardMedicinesRoute._addFileChildren(
    AuthenticatedDashboardMedicinesRouteChildren,
  )

interface AuthenticatedDashboardSalesRouteChildren {
  AuthenticatedDashboardSalesSaleIdRoute: typeof AuthenticatedDashboardSalesSaleIdRoute
}

const AuthenticatedDashboardSalesRouteChildren: AuthenticatedDashboardSalesRouteChildren =
  {
    AuthenticatedDashboardSalesSaleIdRoute:
      AuthenticatedDashboardSalesSaleIdRoute,
  }

const AuthenticatedDashboardSalesRouteWithChildren =
  AuthenticatedDashboardSalesRoute._addFileChildren(
    AuthenticatedDashboardSalesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAiRoute: typeof AuthenticatedDashboardAiRoute
  AuthenticatedDashboardAuditRoute: typeof AuthenticatedDashboardAuditRoute
  AuthenticatedDashboardBatchesRoute: typeof AuthenticatedDashboardBatchesRouteWithChildren
  AuthenticatedDashboardExpiryRoute: typeof AuthenticatedDashboardExpiryRoute
  AuthenticatedDashboardInventoryRoute: typeof AuthenticatedDashboardInventoryRoute
  AuthenticatedDashboardMedicinesRoute: typeof AuthenticatedDashboardMedicinesRouteWithChildren
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardPurchasesRoute: typeof AuthenticatedDashboardPurchasesRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardSalesRoute: typeof AuthenticatedDashboardSalesRouteWithChildren
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardAiRoute: AuthenticatedDashboardAiRoute,
    AuthenticatedDashboardAuditRoute: AuthenticatedDashboardAuditRoute,
    AuthenticatedDashboardBatchesRoute:
      AuthenticatedDashboardBatchesRouteWithChildren,
    AuthenticatedDashboardExpiryRoute: AuthenticatedDashboardExpiryRoute,
    AuthenticatedDashboardInventoryRoute: AuthenticatedDashboardInventoryRoute,
    AuthenticatedDashboardMedicinesRoute:
      AuthenticatedDashboardMedicinesRouteWithChildren,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardPurchasesRoute: AuthenticatedDashboardPurchasesRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardSalesRoute:
      AuthenticatedDashboardSalesRouteWithChildren,
    AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
